// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Root$ReactTemplate = require("./Root.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Root$ReactTemplate.make(/* array */[])), "root");

/*  Not a pure module */
